<template>
  <!-- Render sidebar only if blocks array is not empty -->
  <aside class="sidebar" v-if="blocks && blocks.length > 0">
    <!-- Loop through each block provided in the blocks prop -->
    <div 
      v-for="(block, index) in blocks" 
      :key="`sidebar-block-${index}-${block.title}`" 
      class="sidebar-section"
    >
      <!-- Display the block title if it exists -->
      <h3 v-if="block.title">{{ block.title }}</h3>
      <!-- Render the HTML content using v-html -->
      <!-- IMPORTANT: Ensure HTML content from backend is properly sanitized 
           if it can contain user-generated content to prevent XSS attacks. 
           If content is only admin-generated HTML, v-html is generally acceptable. 
      -->
      <div v-if="block.html_content" v-html="block.html_content"></div>
    </div>
  </aside>
  <!-- Optional: Render a placeholder or nothing if blocks is empty -->
  <div v-else>
    <!-- Sidebar is empty or not applicable -->
  </div>
</template>

<script setup>
// Remove imports that are no longer needed (useI18n, computed)
// import { useI18n } from 'vue-i18n';
// import { computed } from 'vue';

// Define the 'blocks' prop, expecting an array of objects
// Each object should ideally have at least 'html_content' and optionally 'title'
defineProps({
  blocks: {
    type: Array,
    required: true, // Make it required if the parent should always provide it (even if empty)
    default: () => [] // Default to an empty array
  }
});

// Remove the old generateRouteObject method as links are now part of html_content
// const { locale } = useI18n(); 
// const generateRouteObject = (linkTo) => { ... };

</script>

<style scoped>
/* Keep existing styles, they should apply reasonably well to the new structure */
.sidebar {
  flex: 1.5;
  background-color: #f8f9fa;
  padding: 1.5rem;
  border-radius: 8px;
  border: 1px solid #dee2e6;
  height: fit-content;
}

.sidebar-section {
  margin-bottom: 1.5rem;
}
.sidebar-section:last-child {
  margin-bottom: 0;
}
.sidebar-section h3 {
  font-size: 1.1rem;
  margin-bottom: 0.8rem;
  border-bottom: 1px solid #ced4da;
  padding-bottom: 0.4rem;
  color: #495057;
}

/* Target elements potentially generated by v-html (like p, ul, a) */
/* Use :deep() or >>> selector if needed */
.sidebar-section > div > p,
.sidebar-section > div > ul,
.sidebar-section > div > ol {
  margin-bottom: 0.5rem;
  font-size: 0.9rem;
  line-height: 1.4;
}

.sidebar-section > div > ul,
.sidebar-section > div > ol {
  padding-left: 20px;
  margin-top: 0.5rem;
}

.sidebar-section > div > ul > li,
.sidebar-section > div > ol > li {
  margin-bottom: 0.4rem;
}

/* Style links within the v-html content */
.sidebar-section > div a {
  color: #007bff;
  text-decoration: none;
}
.sidebar-section > div a:hover {
  text-decoration: underline;
}

/* Add other specific styles as needed for elements within v-html */

</style> 